spring:
  application:
    name: notification-service
#  rabbitmq:
#    host: ${RABBITMQ_HOST}
#    port: ${RABBITMQ_PORT}
#    username: ${RABBITMQ_USER}
#    password: ${RABBITMQ_PASSWORD}
#    virtual-host: ${RABBITMQ_VHOST}
#    connection-timeout: 30000
  cloud:
    function:
      definition: orderCreated
    stream:
      function:
        definition: orderCreated
      bindings:
        orderCreated-in-0:
          destination: order.exchange
          group: notification-group
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

#rabbitmq:
#  exchange:
#    name: order.exchange
#  queue:
#    name: order.queue
#  routing:
#    key: order.tracking


server:
  port: 8084
