spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
            search-locations: file:///D:\JAVA-spring\MicroServices\ecom-microservices\config-server\src\main\resources\config
server:
  port: 8888
